/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/genkub_greeting_robot.gltf -o src/components/genkub-greeting-robot.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, PerspectiveCamera, OrthographicCamera } from '@react-three/drei'
import { GLTF, SkeletonUtils } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh
    Ears: THREE.Mesh
    Cylinder002: THREE.Mesh
    Mouth: THREE.Mesh
    Eyes: THREE.Mesh
    Head_1: THREE.Mesh
    Head_2: THREE.Mesh
    Headphone_1: THREE.Mesh
    Headphone_2: THREE.Mesh
    Neck: THREE.Mesh
    Body: THREE.Mesh
    Body_Circle_1: THREE.Mesh
    Body_Circle_2: THREE.Mesh
    Arm_R: THREE.Mesh
    HAND_R: THREE.Mesh
    Forearm_R: THREE.Mesh
    Shoulder_R: THREE.Mesh
    Hand_L: THREE.Mesh
    Arm_L: THREE.Mesh
    Forearm_L: THREE.Mesh
    Shoulder_L: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { scene } = useGLTF('/genkub_greeting_robot.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone) as GLTFResult
  // Custom Materials
  const bodyMat = <meshStandardMaterial color="#f8fafc" roughness={0.15} metalness={0.6} envMapIntensity={1} />
  const darkMat = <meshStandardMaterial color="#1e293b" roughness={0.5} metalness={0.8} />
  const accentMat = <meshStandardMaterial color="#3b82f6" roughness={0.2} metalness={0.8} emissive="#1d4ed8" emissiveIntensity={0.5} />
  const glowMat = <meshStandardMaterial color="#60a5fa" emissive="#60a5fa" emissiveIntensity={2} toneMapped={false} />

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[59.064, 150, 96.782]}>
          <directionalLight intensity={0.436} decay={2} color="#f8d6d0" rotation={[-1.266, -0.295, -1.48]} target={nodes.Directional_Light_3.target}>
            <primitive object={nodes.Directional_Light_3.target} position={[0, 0, -1]} />
          </directionalLight>
          <directionalLight intensity={1.769} decay={2} color="#bdddf6" rotation={[-2.756, 0.519, -0.686]} target={nodes.Directional_Light_2.target}>
            <primitive object={nodes.Directional_Light_2.target} position={[0, 0, -1]} />
          </directionalLight>
          <directionalLight intensity={0.29} decay={2} rotation={[-0.398, 0.51, 0.711]} target={nodes.Directional_Light.target}>
            <primitive object={nodes.Directional_Light.target} position={[0, 0, -1]} />
          </directionalLight>
        </group>
        <group position={[27, 7.21, -12]} scale={98.043}>
          <group position={[0, -0.002, 0]} scale={0.01}>
            <group position={[-0.084, 25.17, 0]} rotation={[0, 0, -0.122]} scale={98.043}>
              <group position={[0.001, -0.257, 0]}>
                <mesh geometry={nodes.Cylinder.geometry}>{bodyMat}</mesh>
                <mesh geometry={nodes.Ears.geometry}>{accentMat}</mesh>
                <mesh geometry={nodes.Cylinder002.geometry}>{darkMat}</mesh>
              </group>
              <group position={[0.202, -0.084, 0]} scale={[0.01, 0.008, 0.01]}>
                <mesh geometry={nodes.Mouth.geometry} position={[-19.679, -16.701, 0]} scale={98.043}>{glowMat}</mesh>
              </group>
              <group position={[0.202, -0.019, 0]} scale={0.01}>
                <mesh geometry={nodes.Eyes.geometry} position={[-19.679, -23.054, 0]} scale={98.043}>{glowMat}</mesh>
              </group>
              <mesh geometry={nodes.Head_1.geometry} position={[0.001, -0.255, 0]}>{bodyMat}</mesh>
              <mesh geometry={nodes.Head_2.geometry} position={[0.001, -0.255, 0]}>{darkMat}</mesh>
              <mesh geometry={nodes.Headphone_1.geometry} position={[0.001, -0.255, 0]}>{darkMat}</mesh>
              <mesh geometry={nodes.Headphone_2.geometry} position={[0.001, -0.255, 0]}>{accentMat}</mesh>
            </group>
          </group>
          <group position={[0.012, -0.223, 0]}>
            <mesh geometry={nodes.Neck.geometry} position={[-0.012, 0.223, 0]}>{darkMat}</mesh>
            <mesh geometry={nodes.Body.geometry} position={[-0.012, 0.223, 0]}>{bodyMat}</mesh>
            <mesh geometry={nodes.Body_Circle_1.geometry} position={[-0.012, 0.223, 0]}>{accentMat}</mesh>
            <mesh geometry={nodes.Body_Circle_2.geometry} position={[-0.012, 0.223, 0]}>{darkMat}</mesh>
          </group>
          <group position={[0.032, -0.26, 0.254]}>
            <group position={[-0.016, 0.202, -0.042]}>
              <group position={[0.001, -0.153, 0.054]} scale={0.01}>
                <group position={[1.388, -13.646, 1.559]} scale={98.043}>
                  <mesh geometry={nodes.Arm_R.geometry} position={[-0.01, 0.273, -0.071]}>{bodyMat}</mesh>
                  <mesh geometry={nodes.HAND_R.geometry} position={[-0.01, 0.074, 0.014]} rotation={[Math.PI, -1.571, 0]}>{darkMat}</mesh>
                </group>
              </group>
              <mesh geometry={nodes.Forearm_R.geometry} position={[-0.016, 0.058, -0.212]} rotation={[0.035, 0, 0]} scale={[1, 0.8, 1]}>{bodyMat}</mesh>
            </group>
            <mesh geometry={nodes.Shoulder_R.geometry} position={[-0.032, 0.26, -0.254]}>{bodyMat}</mesh>
          </group>
          <group position={[0.038, -0.295, -0.254]}>
            <mesh geometry={nodes.Hand_L.geometry} position={[-0.032, 0.223, 0.286]} rotation={[0, 0, -0.004]} scale={[0.773, 0.865, 0.892]}>{darkMat}</mesh>
            <mesh geometry={nodes.Arm_L.geometry} position={[-0.038, 0.254, 0.254]}>{bodyMat}</mesh>
            <mesh geometry={nodes.Forearm_L.geometry} position={[-0.038, 0.254, 0.254]}>{bodyMat}</mesh>
            <mesh geometry={nodes.Shoulder_L.geometry} position={[-0.038, 0.254, 0.254]}>{bodyMat}</mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/genkub_greeting_robot.gltf')
